import type { ProjectAudioSettings, ProjectLooks, TextOverlay } from "./project";

export type TemplateCategory =
  | "saas"
  | "keynote"
  | "social"
  | "developer"
  | "tutorial"
  | "teaser"
  | "showcase";

export interface TemplateCustomizableField {
  id: string;
  label: string;
  placeholder: string;
  defaultValue: string;
  type: "text" | "color" | "badge";
}

export interface MotionTemplate {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: TemplateCategory;
  aspectRatio: "16:9" | "9:16" | "1:1" | "4:3";
  accentColor: string;
  badge: string;
  looks: Partial<ProjectLooks>;
  audioSettings: Partial<ProjectAudioSettings>;
  customizableFields: TemplateCustomizableField[];
  defaultTextOverlays: Array<Omit<TextOverlay, "id">>;
}

export const STUDIO_MOTION_TEMPLATES: MotionTemplate[] = [
  {
    id: "saas-launch-hero",
    name: "SaaS Launch Hero",
    tagline: "High-converting dark obsidian launch video with 3D perspective",
    description: "Built for Twitter/X announcements, Product Hunt heroes, and marketing landing pages. Features a subtle 3D tilt, dark mesh gradient, and creamy mechanical keystroke accents.",
    category: "saas",
    aspectRatio: "16:9",
    accentColor: "#6366f1",
    badge: "NEW RELEASE",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #09090b 0%, #1e1b4b 50%, #09090b 100%)",
      padding: 36,
      borderRadius: 18,
      shadow: "glow",
      windowFrame: "macos",
      tiltAngle: 6.5,
      cameraPhysics: "spring",
      cursorStyle: "mac",
      showCursor: true,
      cursorSize: 1.45,
      cursorSmoothing: "cinematic",
      brandAccentColor: "#6366f1",
      mockupUrl: "app.yourstartup.io",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "bop",
      clickSoundVolume: 0.75,
      typingSoundEnabled: true,
      typingSoundPreset: "creamy",
      typingSoundVolume: 0.7,
      musicDuckingEnabled: true,
      duckingAmount: 0.45,
    },
    customizableFields: [
      { id: "headline", label: "Hero Title", placeholder: "Introducing DomoLens 2.0", defaultValue: "Introducing DomoLens 2.0", type: "text" },
      { id: "tagline", label: "Tagline", placeholder: "Studio-quality recordings in seconds", defaultValue: "Studio-quality recordings in seconds", type: "text" },
      { id: "badge", label: "Pill Badge", placeholder: "NEW RELEASE", defaultValue: "NEW RELEASE", type: "badge" },
      { id: "accent", label: "Brand Accent", placeholder: "#6366f1", defaultValue: "#6366f1", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Introducing DomoLens 2.0",
        badge: "NEW RELEASE",
        startTimeMs: 300,
        durationMs: 4000,
        x: 0.5,
        y: 0.08,
        fontSize: 26,
        color: "#ffffff",
        bgColor: "rgba(15, 23, 42, 0.85)",
        style: "headline",
      },
    ],
  },
  {
    id: "apple-keynote-polish",
    name: "Apple Keynote Polish",
    tagline: "Ultra-clean silver gradient, Safari chrome, and cinematic calm",
    description: "The gold standard of minimalist hardware and software presentations. Clean light-mode silver tone with frosted glass window depth and whisper-quiet typing sounds.",
    category: "keynote",
    aspectRatio: "16:9",
    accentColor: "#0071e3",
    badge: "PRO DEMO",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(145deg, #f8fafc 0%, #e2e8f0 100%)",
      padding: 42,
      borderRadius: 16,
      shadow: "lift",
      windowFrame: "safari",
      tiltAngle: 0,
      cameraPhysics: "smooth",
      cursorStyle: "mac",
      showCursor: true,
      cursorSize: 1.35,
      cursorSmoothing: "cinematic",
      brandAccentColor: "#0071e3",
      mockupUrl: "craft.do/workspace",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "click",
      clickSoundVolume: 0.65,
      typingSoundEnabled: true,
      typingSoundPreset: "laptop",
      typingSoundVolume: 0.5,
      musicDuckingEnabled: true,
      duckingAmount: 0.4,
    },
    customizableFields: [
      { id: "headline", label: "Feature Headline", placeholder: "Simplicity, redefined.", defaultValue: "Simplicity, redefined.", type: "text" },
      { id: "tagline", label: "Omnibar URL", placeholder: "craft.do/workspace", defaultValue: "craft.do/workspace", type: "text" },
      { id: "badge", label: "Status Badge", placeholder: "DESIGN REEL", defaultValue: "DESIGN REEL", type: "badge" },
      { id: "accent", label: "Accent Color", placeholder: "#0071e3", defaultValue: "#0071e3", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Simplicity, redefined.",
        badge: "DESIGN REEL",
        startTimeMs: 400,
        durationMs: 3800,
        x: 0.5,
        y: 0.90,
        fontSize: 22,
        color: "#0f172a",
        bgColor: "rgba(255, 255, 255, 0.9)",
        style: "callout",
      },
    ],
  },
  {
    id: "feature-drop-changelog",
    name: "Feature Drop / Changelog",
    tagline: "Snappy rhythmic zoom with violet mesh and feature pills",
    description: "Engineered for weekly shipping updates and release notes. Highlights newly shipped buttons and interactions with energetic clack keystrokes.",
    category: "saas",
    aspectRatio: "16:9",
    accentColor: "#a855f7",
    badge: "v2.4 UPDATE",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #18002a 0%, #2e0854 50%, #0d001a 100%)",
      padding: 32,
      borderRadius: 16,
      shadow: "glow",
      windowFrame: "macos",
      tiltAngle: 4.0,
      cameraPhysics: "snappy",
      cursorStyle: "mac",
      showCursor: true,
      cursorSize: 1.5,
      cursorSmoothing: "smooth",
      brandAccentColor: "#a855f7",
      mockupUrl: "app.linear.app/changelog",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "click",
      clickSoundVolume: 0.75,
      typingSoundEnabled: true,
      typingSoundPreset: "thack",
      typingSoundVolume: 0.65,
      musicDuckingEnabled: true,
      duckingAmount: 0.5,
    },
    customizableFields: [
      { id: "headline", label: "Update Title", placeholder: "Shipped: Instant Auto-Zoom", defaultValue: "Shipped: Instant Auto-Zoom", type: "text" },
      { id: "badge", label: "Version Tag", placeholder: "v2.4 UPDATE", defaultValue: "v2.4 UPDATE", type: "badge" },
      { id: "accent", label: "Accent Color", placeholder: "#a855f7", defaultValue: "#a855f7", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Shipped: Instant Auto-Zoom",
        badge: "v2.4 UPDATE",
        startTimeMs: 200,
        durationMs: 3600,
        x: 0.5,
        y: 0.08,
        fontSize: 24,
        color: "#ffffff",
        bgColor: "rgba(30, 10, 60, 0.85)",
        style: "headline",
      },
    ],
  },
  {
    id: "viral-short-tiktok",
    name: "Viral Short / TikTok Walkthrough",
    tagline: "9:16 vertical story with centered auto-pan and bold captions",
    description: "Optimized for high-retention TikToks, YouTube Shorts, and Instagram Reels. Places the recording in an ergonomic vertical frame with an ambient blurred background.",
    category: "social",
    aspectRatio: "9:16",
    accentColor: "#facc15",
    badge: "MUST WATCH",
    looks: {
      aspectRatio: "9:16",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(180deg, #09090b 0%, #171717 100%)",
      padding: 24,
      borderRadius: 22,
      shadow: "glow",
      windowFrame: "glass",
      tiltAngle: 0,
      cameraPhysics: "snappy",
      cursorStyle: "dot",
      showCursor: true,
      cursorSize: 1.8,
      cursorSmoothing: "smooth",
      brandAccentColor: "#facc15",
      ambientBackdropBlur: true,
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "bop",
      clickSoundVolume: 0.85,
      typingSoundEnabled: true,
      typingSoundPreset: "creamy",
      typingSoundVolume: 0.8,
      musicDuckingEnabled: true,
      duckingAmount: 0.6,
    },
    customizableFields: [
      { id: "headline", label: "Hook Caption", placeholder: "Secret Chrome Shortcut 👇", defaultValue: "Secret Chrome Shortcut 👇", type: "text" },
      { id: "badge", label: "Video Tag", placeholder: "PRO TIP", defaultValue: "PRO TIP", type: "badge" },
      { id: "accent", label: "Highlight Color", placeholder: "#facc15", defaultValue: "#facc15", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Secret Chrome Shortcut 👇",
        badge: "PRO TIP",
        startTimeMs: 100,
        durationMs: 5000,
        x: 0.5,
        y: 0.12,
        fontSize: 26,
        color: "#ffffff",
        bgColor: "rgba(0, 0, 0, 0.85)",
        style: "headline",
      },
    ],
  },
  {
    id: "developer-cli",
    name: "Developer CLI Deep-Dive",
    tagline: "Monochrome cyberpunk terminal with deep POM mechanical thocks",
    description: "Designed for open-source repositories, developer tools, and terminal CLIs. Features authentic mechanical thock acoustics and high-contrast terminal framing.",
    category: "developer",
    aspectRatio: "16:9",
    accentColor: "#22c55e",
    badge: "CLI TOOL",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #050b07 0%, #0d1a10 50%, #050b07 100%)",
      padding: 34,
      borderRadius: 14,
      shadow: "lift",
      windowFrame: "terminal",
      tiltAngle: 3.5,
      cameraPhysics: "spring",
      cursorStyle: "dot",
      showCursor: true,
      cursorSize: 1.4,
      cursorSmoothing: "smooth",
      brandAccentColor: "#22c55e",
      mockupUrl: "terminal — zsh — 80x24",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "tap",
      clickSoundVolume: 0.7,
      typingSoundEnabled: true,
      typingSoundPreset: "thock",
      typingSoundVolume: 0.85,
      musicDuckingEnabled: true,
      duckingAmount: 0.45,
    },
    customizableFields: [
      { id: "headline", label: "Command Title", placeholder: "$ npx create-domo-app", defaultValue: "$ npx create-domo-app", type: "text" },
      { id: "badge", label: "Branch / Tag", placeholder: "v1.0 • Node 22", defaultValue: "v1.0 • Node 22", type: "badge" },
      { id: "accent", label: "Terminal Green", placeholder: "#22c55e", defaultValue: "#22c55e", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "$ npx create-domo-app",
        badge: "v1.0 RELEASE",
        startTimeMs: 300,
        durationMs: 4200,
        x: 0.5,
        y: 0.08,
        fontSize: 22,
        color: "#22c55e",
        bgColor: "rgba(5, 15, 10, 0.9)",
        style: "headline",
      },
    ],
  },
  {
    id: "micro-tutorial",
    name: "30-Second Micro-Tutorial",
    tagline: "Structured step-by-step numbered callouts for documentation",
    description: "The ideal template for user documentation, knowledge base articles, and onboarding steps. Provides clean numbered step pills that guide viewer focus.",
    category: "tutorial",
    aspectRatio: "16:9",
    accentColor: "#0ea5e9",
    badge: "STEP-BY-STEP",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #0b192c 0%, #1e3a5f 100%)",
      padding: 36,
      borderRadius: 16,
      shadow: "lift",
      windowFrame: "macos",
      tiltAngle: 0,
      cameraPhysics: "smooth",
      cursorStyle: "mac",
      showCursor: true,
      cursorSize: 1.5,
      cursorSmoothing: "cinematic",
      brandAccentColor: "#0ea5e9",
      mockupUrl: "help.domolens.dev/guides",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "tap",
      clickSoundVolume: 0.7,
      typingSoundEnabled: true,
      typingSoundPreset: "creamy",
      typingSoundVolume: 0.6,
      musicDuckingEnabled: true,
      duckingAmount: 0.5,
    },
    customizableFields: [
      { id: "headline", label: "Step 1 Text", placeholder: "Step 1: Open Settings Panel", defaultValue: "Step 1: Open Settings Panel", type: "text" },
      { id: "badge", label: "Step Badge", placeholder: "TUTORIAL", defaultValue: "TUTORIAL", type: "badge" },
      { id: "accent", label: "Sky Accent", placeholder: "#0ea5e9", defaultValue: "#0ea5e9", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Step 1: Click Settings to configure audio",
        badge: "STEP 1 OF 3",
        startTimeMs: 400,
        durationMs: 4500,
        x: 0.5,
        y: 0.90,
        fontSize: 22,
        color: "#ffffff",
        bgColor: "rgba(11, 25, 44, 0.9)",
        style: "callout",
      },
    ],
  },
  {
    id: "product-hunt-teaser",
    name: "Product Hunt Teaser",
    tagline: "High-octane warm sunset gradient with clicky tactile switches",
    description: "Built to drive launch-day upvotes. Features rhythmic fast zooms, high-energy clicky switch sounds, and bright energetic typography.",
    category: "teaser",
    aspectRatio: "1:1",
    accentColor: "#ea580c",
    badge: "LIVE TODAY",
    looks: {
      aspectRatio: "1:1",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #431407 0%, #9a3412 50%, #ea580c 100%)",
      padding: 30,
      borderRadius: 20,
      shadow: "glow",
      windowFrame: "macos",
      tiltAngle: 5.0,
      cameraPhysics: "spring",
      cursorStyle: "mac",
      showCursor: true,
      cursorSize: 1.6,
      cursorSmoothing: "smooth",
      brandAccentColor: "#ea580c",
      mockupUrl: "producthunt.com/posts/domolens",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "click",
      clickSoundVolume: 0.85,
      typingSoundEnabled: true,
      typingSoundPreset: "clicky",
      typingSoundVolume: 0.75,
      musicDuckingEnabled: true,
      duckingAmount: 0.55,
    },
    customizableFields: [
      { id: "headline", label: "Launch Tagline", placeholder: "We are live on Product Hunt! 🚀", defaultValue: "We are live on Product Hunt! 🚀", type: "text" },
      { id: "badge", label: "Badge Tag", placeholder: "FEATURED #1", defaultValue: "FEATURED #1", type: "badge" },
      { id: "accent", label: "Brand Orange", placeholder: "#ea580c", defaultValue: "#ea580c", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "We are live on Product Hunt! 🚀",
        badge: "FEATURED #1",
        startTimeMs: 200,
        durationMs: 4000,
        x: 0.5,
        y: 0.08,
        fontSize: 24,
        color: "#ffffff",
        bgColor: "rgba(40, 15, 5, 0.9)",
        style: "headline",
      },
    ],
  },
  {
    id: "enterprise-security",
    name: "Enterprise Security Demo",
    tagline: "Navy slate palette with privacy blur and silenced keystrokes",
    description: "Designed for enterprise procurement and security whitepapers. Features calm, measured camera transitions and silenced thick mechanical acoustics.",
    category: "saas",
    aspectRatio: "16:9",
    accentColor: "#38bdf8",
    badge: "SOC2 TYPE II",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
      padding: 38,
      borderRadius: 14,
      shadow: "lift",
      windowFrame: "macos",
      tiltAngle: 0,
      cameraPhysics: "smooth",
      cursorStyle: "mac",
      showCursor: true,
      cursorSize: 1.3,
      cursorSmoothing: "cinematic",
      brandAccentColor: "#38bdf8",
      mockupUrl: "enterprise.portal.corp",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "tap",
      clickSoundVolume: 0.6,
      typingSoundEnabled: true,
      typingSoundPreset: "thick",
      typingSoundVolume: 0.65,
      musicDuckingEnabled: true,
      duckingAmount: 0.4,
    },
    customizableFields: [
      { id: "headline", label: "Compliance Headline", placeholder: "Role-Based Access Control (RBAC)", defaultValue: "Role-Based Access Control (RBAC)", type: "text" },
      { id: "badge", label: "Security Badge", placeholder: "ENTERPRISE", defaultValue: "ENTERPRISE", type: "badge" },
      { id: "accent", label: "Corporate Blue", placeholder: "#38bdf8", defaultValue: "#38bdf8", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Role-Based Access Control (RBAC)",
        badge: "SOC2 COMPLIANT",
        startTimeMs: 400,
        durationMs: 4200,
        x: 0.5,
        y: 0.08,
        fontSize: 22,
        color: "#ffffff",
        bgColor: "rgba(15, 23, 42, 0.9)",
        style: "headline",
      },
    ],
  },
  {
    id: "interactive-click",
    name: "Interactive Click Showcase",
    tagline: "Micro-interaction focus with radar ripples and bubble bops",
    description: "Highlights tactile UI responsiveness. Every click generates an expanding sonar pulse synchronized with bubbly low-end bop audio feedback.",
    category: "showcase",
    aspectRatio: "16:9",
    accentColor: "#06b6d4",
    badge: "INTERACTIONS",
    looks: {
      aspectRatio: "16:9",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #082f49 0%, #0c4a6e 50%, #031826 100%)",
      padding: 34,
      borderRadius: 18,
      shadow: "glow",
      windowFrame: "glass",
      tiltAngle: 4.5,
      cameraPhysics: "spring",
      cursorStyle: "ring",
      showCursor: true,
      showClickRipples: true,
      cursorSize: 1.55,
      cursorSmoothing: "smooth",
      brandAccentColor: "#06b6d4",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "bop",
      clickSoundVolume: 0.85,
      typingSoundEnabled: true,
      typingSoundPreset: "creamy",
      typingSoundVolume: 0.7,
      musicDuckingEnabled: true,
      duckingAmount: 0.5,
    },
    customizableFields: [
      { id: "headline", label: "Callout Title", placeholder: "Zero-Latency Micro Interactions", defaultValue: "Zero-Latency Micro Interactions", type: "text" },
      { id: "badge", label: "Feature Pill", placeholder: "TACTILE UI", defaultValue: "TACTILE UI", type: "badge" },
      { id: "accent", label: "Cyan Tone", placeholder: "#06b6d4", defaultValue: "#06b6d4", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Zero-Latency Micro Interactions",
        badge: "TACTILE UI",
        startTimeMs: 300,
        durationMs: 3800,
        x: 0.5,
        y: 0.08,
        fontSize: 24,
        color: "#ffffff",
        bgColor: "rgba(8, 47, 73, 0.9)",
        style: "headline",
      },
    ],
  },
  {
    id: "dribbble-design-reel",
    name: "Dribbble Design Reel",
    tagline: "Pastel lavender aesthetic in 4:3 with floating soft shadows",
    description: "Crafted specifically for design portfolios and Dribbble/Twitter design showcases. Elegant pastel hues, multi-layer soft shadows, and lubed creamy typing sounds.",
    category: "showcase",
    aspectRatio: "4:3",
    accentColor: "#ec4899",
    badge: "FIGMA REEL",
    looks: {
      aspectRatio: "4:3",
      backgroundType: "gradient",
      backgroundValue: "linear-gradient(135deg, #fdf2f8 0%, #fae8ff 50%, #ede9fe 100%)",
      padding: 44,
      borderRadius: 24,
      shadow: "lift",
      windowFrame: "glass",
      tiltAngle: 5.5,
      cameraPhysics: "smooth",
      cursorStyle: "dot",
      showCursor: true,
      cursorSize: 1.4,
      cursorSmoothing: "cinematic",
      brandAccentColor: "#ec4899",
      mockupUrl: "figma.com/@studio/design-system",
    },
    audioSettings: {
      clickSoundEnabled: true,
      clickSoundPreset: "tap",
      clickSoundVolume: 0.6,
      typingSoundEnabled: true,
      typingSoundPreset: "creamy",
      typingSoundVolume: 0.65,
      musicDuckingEnabled: true,
      duckingAmount: 0.4,
    },
    customizableFields: [
      { id: "headline", label: "Design System Title", placeholder: "Design System v3.0 by Studio", defaultValue: "Design System v3.0 by Studio", type: "text" },
      { id: "badge", label: "Badge Label", placeholder: "FIGMA PRO", defaultValue: "FIGMA PRO", type: "badge" },
      { id: "accent", label: "Pastel Pink", placeholder: "#ec4899", defaultValue: "#ec4899", type: "color" },
    ],
    defaultTextOverlays: [
      {
        text: "Design System v3.0 by Studio",
        badge: "FIGMA PRO",
        startTimeMs: 400,
        durationMs: 4200,
        x: 0.5,
        y: 0.90,
        fontSize: 22,
        color: "#831843",
        bgColor: "rgba(255, 255, 255, 0.92)",
        style: "callout",
      },
    ],
  },
];
